<?php

namespace Database\Seeders;

use App\Structure\ReportingSection\Admin\Models\Mundebt;
use Illuminate\Database\Seeder;

class MundebtsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Mundebt::insert([
            [
                'year'       => 2020,
                'mounth'     => 1,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],   
            [
                'year'       => 2020,
                'mounth'     => 2,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2020,
                'mounth'     => 3,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2020,
                'mounth'     => 4,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2020,
                'mounth'     => 5,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2020,
                'mounth'     => 6,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2020,
                'mounth'     => 7,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2020,
                'mounth'     => 8,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2020,
                'mounth'     => 9,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2020,
                'mounth'     => 10,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2020,
                'mounth'     => 11,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2020,
                'mounth'     => 12,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2021,
                'mounth'     => 1,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2021,
                'mounth'     => 2,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2021,
                'mounth'     => 3,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2021,
                'mounth'     => 4,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2021,
                'mounth'     => 5,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2021,
                'mounth'     => 6,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2021,
                'mounth'     => 7,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2021,
                'mounth'     => 8,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2021,
                'mounth'     => 9,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2021,
                'mounth'     => 10,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2021,
                'mounth'     => 11,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2021,
                'mounth'     => 12,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2022,
                'mounth'     => 1,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2022,
                'mounth'     => 2,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2022,
                'mounth'     => 3,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2022,
                'mounth'     => 4,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2022,
                'mounth'     => 5,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2022,
                'mounth'     => 6,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2022,
                'mounth'     => 7,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2022,
                'mounth'     => 8,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2022,
                'mounth'     => 9,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2022,
                'mounth'     => 10,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2022,
                'mounth'     => 11,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2022,
                'mounth'     => 12,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2023,
                'mounth'     => 1,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2023,
                'mounth'     => 2,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2023,
                'mounth'     => 3,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2023,
                'mounth'     => 4,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2023,
                'mounth'     => 5,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2023,
                'mounth'     => 6,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2023,
                'mounth'     => 7,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2023,
                'mounth'     => 8,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2023,
                'mounth'     => 9,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2023,
                'mounth'     => 10,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2023,
                'mounth'     => 11,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
            [
                'year'       => 2023,
                'mounth'     => 12,
                'mundeb'     => 0,
                'servmundeb' => 0,
                'maxmunded'  => 0,
                'bank'       => 0,
                'credit'     => 0,
            ],
        ]);
    }
    
}

